language: node_js
sudo: false
node_js:
- '10'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_2e74059a464c_key -iv $encrypted_2e74059a464c_iv
  -in .travis/id_rsa_travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'biless'
- git config --global user.email biless@qq.com
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
